
%NOTE: make sure this compile option is included in the COMPFLAGS variable: 
%         /assume:byterecl 

NWTC_LIB    = 'D:\DATA\DesignCodes\miscellaneous\nwtc_subs\SVNtrunk\source';
WIND_LOC    = 'D:\DATA\DesignCodes\simulators\InflowWind\SVNdirectory\trunk\Source';

mex('-v', ...
    '-f','intelf10msvs2003opts.bat', ...
    '-output', 'InflowWind_mex',...
    [NWTC_LIB '\DoubPrec.f90'           ], ... 
    [NWTC_LIB '\SysMatlab.f90'          ], ...
    [NWTC_LIB '\NWTC_IO.f90'            ], ...
    [NWTC_LIB '\NWTC_Num.f90'           ], ...
    [NWTC_LIB '\NWTC_Aero.f90'          ], ...
    [NWTC_LIB '\NWTC_Library.f90'       ], ...
    [WIND_LOC '\SharedInflowDefs.f90'   ], ...
    [WIND_LOC '\HHWind.f90'             ], ...
    [WIND_LOC '\FFWind.f90'             ], ...
    [WIND_LOC '\HAWCWind.f90'           ], ...
    [WIND_LOC '\FDWind.f90'             ], ...
    [WIND_LOC '\CTWind.f90'             ], ...
    [WIND_LOC '\UserWind.f90'           ], ...
    [WIND_LOC '\InflowWindMod.f90'      ], ...
    'InflowWind_Gateway.f90'            );

delete ('*.mod')
disp('mex completed')
