This mode-shape file was generated by modes v2.22 (29-Apr-2002) on 10-Oct-2015 at 17:43:50.
Results are based upon data input from "WP5.0A04V00_BldModes.inp".

Rigid beam length (m)    =     3.200
Flexible beam length (m) =    60.800
Total beam length (m)    =    64.000
End mass (kg)            =     0.000
Rotor speed (rpm)        =    11.191
Pitch angle (deg)        =     0.000
Mass multiplier          =     1.000
Flatwise stiffness mult. =     1.000
Edgewise stiffness mult. =     1.000


Out-of-plane mode shapes:

               Shape 1     Shape 2     Shape 3     Shape 4     Shape 5
               -------     -------     -------     -------     -------
 Freq (hz)      0.7924      2.2874      5.3218     11.0855     33.7128

    x^2         0.1627     -0.4863      0.2652     -1.0055     31.4977
    x^3         1.6395     -1.4363     20.3135    -13.6311   -229.1162
    x^4        -2.1560     -4.3687    -75.4831     81.5252    584.5727
    x^5         2.6749     15.8464     84.1922   -131.9190   -628.2911
    x^6        -1.3210     -8.5552    -28.2878     66.0305    242.3370


In-plane mode shapes:

               Shape 1     Shape 2     Shape 3     Shape 4     Shape 5
               -------     -------     -------     -------     -------
 Freq (hz)      1.1611      3.5027      8.4328     20.7294     40.9375

    x^2         0.5594     -1.2221      1.1769     -6.0781     22.1374
    x^3         1.7444     -1.8558     22.2931     23.6522   -166.6316
    x^4        -4.5923      3.1416    -98.5891    -12.1516    437.7841
    x^5         5.9295      5.8671    123.7256    -34.2806   -482.6505
    x^6        -2.6411     -4.9307    -47.6064     29.8580    190.3606
