This mode-shape file was generated by modes v2.22 (29-Apr-2002) on 19-Oct-2015 at 17:16:18.
Results are based upon data input from "WP5.0A04V00_BldModes.inp".

Rigid beam length (m)    =     3.200
Flexible beam length (m) =    60.800
Total beam length (m)    =    64.000
End mass (kg)            =     0.000
Rotor speed (rpm)        =    11.191
Pitch angle (deg)        =     0.000
Mass multiplier          =     1.000
Flatwise stiffness mult. =     1.000
Edgewise stiffness mult. =     1.000


Out-of-plane mode shapes:

               Shape 1     Shape 2     Shape 3     Shape 4     Shape 5
               -------     -------     -------     -------     -------
 Freq (hz)      0.7914      2.2926      5.3268     11.0220     29.8245

    x^2         0.1532     -0.4652      0.1938     -0.7631     34.5490
    x^3         1.7158     -1.6179     20.9914    -14.7479   -247.7130
    x^4        -2.3131     -3.9428    -77.5599     83.1078    624.8425
    x^5         2.8084     15.4805     86.7207   -132.5775   -665.4375
    x^6        -1.3643     -8.4547    -29.3460     65.9807    254.7590


In-plane mode shapes:

               Shape 1     Shape 2     Shape 3     Shape 4     Shape 5
               -------     -------     -------     -------     -------
 Freq (hz)      1.1618      3.5145      8.4424     20.8244     36.0010

    x^2         0.5418     -1.1939      1.0749     -5.9071     21.3831
    x^3         1.8285     -2.0479     23.1697     22.7055   -160.3655
    x^4        -4.7455      3.5392   -101.0700    -10.4066    420.6530
    x^5         6.0593      5.5451    126.5731    -35.5425   -463.6448
    x^6        -2.6841     -4.8426    -48.7477     30.1507    182.9742
