This mode-shape file was generated by modes v2.22 (29-Apr-2002) on 19-Oct-2015 at 17:16:23.
Results are based upon data input from "WP5.0A04V00_TwrModes.inp".

Rigid beam length (m)    =     0.000
Flexible beam length (m) =   151.072
Total beam length (m)    =   151.072
End mass (kg)            =396638.344
Mass multiplier          =     1.000
Stiffness multiplier     =     1.000

               Shape 1     Shape 2     Shape 3     Shape 4     Shape 5
               -------     -------     -------     -------     -------
 Freq (hz)      0.2420      1.6097      4.6207     10.8472     17.5109

    x^2         0.6664    -21.1745     80.6049   -672.7549   1201.1929
    x^3         0.5297     14.8974    245.9512   3430.4993  -8902.8047
    x^4        -0.7717    -28.9293  -1551.2170  -5663.1274  22748.8809
    x^5         1.2096     76.9609   1954.5756   3427.4692 -24177.1875
    x^6        -0.6340    -40.7545   -728.9145   -521.0861   9130.9189
