This mode-shape file was generated by modes v2.22 (29-Apr-2002) on 11-Oct-2015 at 19:28:29.
Results are based upon data input from "WP1.5A08V03_TwrModes.inp".

Rigid beam length (m)    =     0.000
Flexible beam length (m) =    82.390
Total beam length (m)    =    82.390
End mass (kg)            = 72025.781
Mass multiplier          =     1.000
Stiffness multiplier     =     1.000

               Shape 1     Shape 2     Shape 3     Shape 4     Shape 5
               -------     -------     -------     -------     -------
 Freq (hz)      0.4324      3.0140      8.7104     21.4192     96.0976

    x^2         0.7475    -22.7510     96.1581   -553.0963   2886.3469
    x^3         0.4482     13.3410    173.4863   2689.5959 -20283.3555
    x^4        -0.5802    -13.3723  -1437.0621  -4069.0725  49481.1953
    x^5         0.8546     57.9585   1889.0758   1989.3463 -50540.0586
    x^6        -0.4701    -34.1762   -720.6580    -55.7734  18456.8730
