This mode-shape file was generated by modes v2.22 (29-Apr-2002) on 19-Oct-2015 at 14:10:32.
Results are based upon data input from "WP1.5A08V03_BldModes.inp".

Rigid beam length (m)    =     1.750
Flexible beam length (m) =    33.250
Total beam length (m)    =    35.000
End mass (kg)            =     0.000
Rotor speed (rpm)        =    20.463
Pitch angle (deg)        =     0.000
Mass multiplier          =     1.000
Flatwise stiffness mult. =     1.000
Edgewise stiffness mult. =     1.000


Out-of-plane mode shapes:

               Shape 1     Shape 2     Shape 3     Shape 4     Shape 5
               -------     -------     -------     -------     -------
 Freq (hz)      1.3204      3.8518      8.9838     18.3177     69.8198

    x^2         0.0836     -0.2983      0.0456     -0.5084     38.0115
    x^3         1.7116     -2.1187     22.6220    -20.5520   -273.9933
    x^4        -1.7172     -4.2140    -79.8411    105.2138    692.8907
    x^5         1.8252     16.4481     85.8367   -161.8830   -738.2792
    x^6        -0.9031     -8.8172    -27.6632     78.7296    282.3704


In-plane mode shapes:

               Shape 1     Shape 2     Shape 3     Shape 4     Shape 5
               -------     -------     -------     -------     -------
 Freq (hz)      1.9466      6.5427     15.1735     40.8681     80.3251

    x^2         0.3199     -0.8084      1.0240     -6.7560     25.5127
    x^3         3.3166     -6.8588     28.5689     26.4188   -190.4414
    x^4        -6.5890     16.9893   -122.3914    -14.4607    496.6380
    x^5         6.2413     -8.5328    153.8075    -36.0336   -543.7565
    x^6        -2.2889      0.2108    -60.0090     31.8315    213.0472
