This mode-shape file was generated by modes v2.22 (29-Apr-2002) on 19-Oct-2015 at 15:26:48.
Results are based upon data input from "WP0.75A08V00_BldModes.inp".

Rigid beam length (m)    =     1.250
Flexible beam length (m) =    23.750
Total beam length (m)    =    25.000
End mass (kg)            =     0.000
Rotor speed (rpm)        =    28.648
Pitch angle (deg)        =     0.000
Mass multiplier          =     1.000
Flatwise stiffness mult. =     1.000
Edgewise stiffness mult. =     1.000


Out-of-plane mode shapes:

               Shape 1     Shape 2     Shape 3     Shape 4     Shape 5
               -------     -------     -------     -------     -------
 Freq (hz)      1.7218      5.1274     11.8264     24.7935    110.6762

    x^2         0.0734     -0.2631      0.0249     -0.6449     35.8015
    x^3         1.9794     -3.0048     25.0855    -19.8875   -261.0547
    x^4        -2.0944     -1.6250    -89.6602    104.3659    665.8568
    x^5         1.8681     13.8375     98.5515   -161.7626   -714.1277
    x^6        -0.8264     -7.9446    -33.0017     78.9290    274.5242


In-plane mode shapes:

               Shape 1     Shape 2     Shape 3     Shape 4     Shape 5
               -------     -------     -------     -------     -------
 Freq (hz)      2.5527      8.8747     20.5833     56.6008    137.1207

    x^2         0.3044     -0.8025      1.1786     -7.4393     26.8613
    x^3         3.8089     -8.1986     28.4475     30.7226   -201.4135
    x^4        -7.7479     21.5906   -123.9398    -23.8005    526.0615
    x^5         7.1872    -13.7334    156.8134    -27.5604   -575.8378
    x^6        -2.5527      2.1439    -61.4998     29.0775    225.3285
