This mode-shape file was generated by modes v2.22 (29-Apr-2002) on 20-Nov-2015 at 11:30:15.
Results are based upon data input from "WP0.75A08V00_TwrModes.inp".

Rigid beam length (m)    =     0.000
Flexible beam length (m) =    58.670
Total beam length (m)    =    58.670
End mass (kg)            = 27524.180
Mass multiplier          =     1.000
Stiffness multiplier     =     1.000

               Shape 1     Shape 2     Shape 3     Shape 4     Shape 5
               -------     -------     -------     -------     -------
 Freq (hz)      0.6622      4.2304     12.1184     27.6740     45.7869

    x^2         0.8126    -18.8410     75.8006   -838.0206    553.6741
    x^3         0.3864      9.0469    127.2768   4770.0679  -4352.1807
    x^4        -0.4449      2.7752  -1121.8251  -9317.7500  11627.2480
    x^5         0.5874     28.8580   1502.2903   7507.1338 -12786.7695
    x^6        -0.3416    -20.8391   -582.5425  -2120.4312   4959.0288
