This mode-shape file was generated by modes v2.22 (29-Apr-2002) on 10-Oct-2015 at 17:16:06.
Results are based upon data input from "WP1.5A08V03_BldModes.inp".

Rigid beam length (m)    =     1.750
Flexible beam length (m) =    33.250
Total beam length (m)    =    35.000
End mass (kg)            =     0.000
Rotor speed (rpm)        =    20.463
Pitch angle (deg)        =     0.000
Mass multiplier          =     1.000
Flatwise stiffness mult. =     1.000
Edgewise stiffness mult. =     1.000


Out-of-plane mode shapes:

               Shape 1     Shape 2     Shape 3     Shape 4     Shape 5
               -------     -------     -------     -------     -------
 Freq (hz)      1.3223      3.8445      8.9626     18.3299     64.6992

    x^2         0.0917     -0.3186      0.0899     -0.5483     39.2204
    x^3         1.6437     -1.9402     22.4426    -20.4641   -281.5977
    x^4        -1.5849     -4.6477    -79.5050    105.4433    709.9905
    x^5         1.7225     16.8372     85.4759   -162.5358   -754.7132
    x^6        -0.8730     -8.9307    -27.5033     79.1049    288.1000


In-plane mode shapes:

               Shape 1     Shape 2     Shape 3     Shape 4     Shape 5
               -------     -------     -------     -------     -------
 Freq (hz)      1.9470      6.5269     15.1254     40.6929     76.9398

    x^2         0.3384     -0.8480      1.0836     -7.2572     24.5691
    x^3         3.2245     -6.5872     28.1399     29.5398   -184.1225
    x^4        -6.4186     16.3945   -121.2887    -21.2586    481.8857
    x^5         6.0995     -8.0069    152.5994    -29.7997   -529.2895
    x^6        -2.2438      0.0477    -59.5341     29.7757    207.9571
