This mode-shape file was generated by modes v2.22 (29-Apr-2002) on 20-Oct-2015 at 08:47:24.
Results are based upon data input from "WP3.0A02V02_BldModes.inp".

Rigid beam length (m)    =     2.480
Flexible beam length (m) =    47.020
Total beam length (m)    =    49.500
End mass (kg)            =     0.000
Rotor speed (rpm)        =    14.469
Pitch angle (deg)        =     0.000
Mass multiplier          =     1.000
Flatwise stiffness mult. =     1.000
Edgewise stiffness mult. =     1.000


Out-of-plane mode shapes:

               Shape 1     Shape 2     Shape 3     Shape 4     Shape 5
               -------     -------     -------     -------     -------
 Freq (hz)      0.9929      2.8761      6.7378     14.2347     78.7391

    x^2         0.1316     -0.4122      0.2060     -1.2033     26.4642
    x^3         1.7964     -1.8511     20.2383    -14.0134   -198.4733
    x^4        -2.4283     -3.6350    -73.7887     85.6534    518.2602
    x^5         2.8637     15.2195     80.8676   -138.6484   -567.1115
    x^6        -1.3634     -8.3212    -26.5232     69.2117    221.8604


In-plane mode shapes:

               Shape 1     Shape 2     Shape 3     Shape 4     Shape 5
               -------     -------     -------     -------     -------
 Freq (hz)      1.4357      4.5222     10.7931     27.3291     97.1297

    x^2         0.4636     -1.0383      1.2280     -6.3632     23.7622
    x^3         2.3733     -3.8036     23.6400     25.0547   -180.2413
    x^4        -5.3510      8.4390   -104.6713    -14.4394    475.0767
    x^5         5.9815      0.3921    131.9119    -32.8998   -523.9935
    x^6        -2.4674     -2.9892    -51.1086     29.6476    206.3959
