This mode-shape file was generated by modes v2.22 (29-Apr-2002) on 20-Oct-2015 at 08:47:31.
Results are based upon data input from "WP3.0A02V02_TwrModes.inp".

Rigid beam length (m)    =     0.000
Flexible beam length (m) =   116.731
Total beam length (m)    =   116.731
End mass (kg)            =194268.375
Mass multiplier          =     1.000
Stiffness multiplier     =     1.000

               Shape 1     Shape 2     Shape 3     Shape 4     Shape 5
               -------     -------     -------     -------     -------
 Freq (hz)      0.3138      2.1553      6.2220     14.8649     38.9186

    x^2         0.7047    -22.7140     94.0248   -640.1746   1909.2920
    x^3         0.4989     14.2601    200.0876   3228.0593 -13836.5215
    x^4        -0.6982    -20.5256  -1512.7758  -5209.0186  34636.0195
    x^5         1.0562     68.1210   1962.1394   2988.8889 -36150.3984
    x^6        -0.5615    -38.1414   -742.4760   -366.7549  13442.6094
