This mode-shape file was generated by modes v2.22 (29-Apr-2002) on 19-Oct-2015 at 15:26:56.
Results are based upon data input from "WP0.75A08V00_TwrModes.inp".

Rigid beam length (m)    =     0.000
Flexible beam length (m) =    58.670
Total beam length (m)    =    58.670
End mass (kg)            = 27524.180
Mass multiplier          =     1.000
Stiffness multiplier     =     1.000

               Shape 1     Shape 2     Shape 3     Shape 4     Shape 5
               -------     -------     -------     -------     -------
 Freq (hz)      0.6080      4.1640     12.0732     30.2127    108.4010

    x^2         0.8565    -21.2343     96.9202   -558.6855   2648.5273
    x^3         0.3405      9.1047     57.2743   2936.7488 -18615.5469
    x^4        -0.3646     10.9918  -1053.8053  -5094.7754  45365.3633
    x^5         0.4347     20.7935   1489.1040   3398.5837 -46262.4023
    x^6        -0.2671    -18.6557   -588.4931   -680.8717  16865.0586
