This mode-shape file was generated by modes v2.22 (29-Apr-2002) on 10-Oct-2015 at 15:35:53.
Results are based upon data input from "0.75A08V00_BldModes.inp".

Rigid beam length (m)    =     1.250
Flexible beam length (m) =    23.750
Total beam length (m)    =    25.000
End mass (kg)            =     0.000
Rotor speed (rpm)        =    28.648
Pitch angle (deg)        =     0.000
Mass multiplier          =     1.000
Flatwise stiffness mult. =     1.000
Edgewise stiffness mult. =     1.000


Out-of-plane mode shapes:

               Shape 1     Shape 2     Shape 3     Shape 4     Shape 5
               -------     -------     -------     -------     -------
 Freq (hz)      1.7244      5.1179     11.7987     24.8234    106.1832

    x^2         0.0820     -0.2845      0.0784     -0.7192     36.1642
    x^3         1.9097     -2.8178     24.8330    -19.5947   -263.4413
    x^4        -1.9581     -2.0802    -89.1359    104.1561    671.4948
    x^5         1.7615     14.2497     97.9946   -162.0100   -719.8190
    x^6        -0.7951     -8.0672    -32.7700     79.1677    276.6013


In-plane mode shapes:

               Shape 1     Shape 2     Shape 3     Shape 4     Shape 5
               -------     -------     -------     -------     -------
 Freq (hz)      2.5526      8.8531     20.5182     56.3533    133.6065

    x^2         0.3243     -0.8462      1.2546     -7.8906     26.3120
    x^3         3.7154     -7.9082     27.8943     33.5458   -197.8478
    x^4        -7.5799     20.9670   -122.5287    -29.9650    517.9998
    x^5         7.0494    -13.1882    155.2931    -21.9012   -568.1813
    x^6        -2.5092      1.9755    -60.9134     27.2110    222.7174
