This mode-shape file was generated by modes v2.22 (29-Apr-2002) on 10-Oct-2015 at 17:41:17.
Results are based upon data input from "WP3.0A02V02_BldModes.inp".

Rigid beam length (m)    =     2.480
Flexible beam length (m) =    47.020
Total beam length (m)    =    49.500
End mass (kg)            =     0.000
Rotor speed (rpm)        =    14.469
Pitch angle (deg)        =     0.000
Mass multiplier          =     1.000
Flatwise stiffness mult. =     1.000
Edgewise stiffness mult. =     1.000


Out-of-plane mode shapes:

               Shape 1     Shape 2     Shape 3     Shape 4     Shape 5
               -------     -------     -------     -------     -------
 Freq (hz)      0.9942      2.8694      6.6985     13.9018     46.5659

    x^2         0.1408     -0.4348      0.2146     -0.9102     32.7494
    x^3         1.7234     -1.6487     20.7042    -15.6548   -238.0702
    x^4        -2.2825     -4.1359    -75.6870     89.0267    606.9101
    x^5         2.7443     15.6836     83.2675   -141.6927   -651.6208
    x^6        -1.3260     -8.4641    -27.4994     70.2310    251.0314


In-plane mode shapes:

               Shape 1     Shape 2     Shape 3     Shape 4     Shape 5
               -------     -------     -------     -------     -------
 Freq (hz)      1.4353      4.5087     10.7058     27.2010     54.1035

    x^2         0.4826     -1.0706      1.1596     -6.5089     23.1591
    x^3         2.2785     -3.5810     24.3603     25.8677   -173.7946
    x^4        -5.1705      7.9648   -106.8183    -15.9430    455.4721
    x^5         5.8240      0.7926    134.3609    -31.8145   -501.0442
    x^6        -2.4146     -3.1059    -52.0626     29.3987    197.2076
